### ISSUE TITLE
React community join request

### ISSUE THREAD

**Issue by mevolkan** [reactdeveloperske/community-support#10]
Hi, I am a rookie REACT dev and would like to join the community and grow my skill contributing to open source

**Comment by stephanieopala** [comment]
Hello @mevolkan 
You will be added shortly. 
You can also join our telegram group using this [link](http://bit.ly/joinreactdevske)

**Comment by mevolkan** [comment]
thank you

**Comment by stephanieopala** [comment]
@orama254
