### ISSUE TITLE
I'd like to join the community

### ISSUE THREAD

**Issue by dmithamo** [reactdeveloperske/community-support#6]
Hello!
I have been a React dev for a while now, working mostly on internal tooling for my employer.
I would love to be a part of this community to help build cool stuff while honing my skills as a developer.
Thanks!

**Comment by orama254** [comment]
Hi @dmithamo ,

You will be added to the Org shortly.

You can also checkout This [Invitation Link](http://bit.ly/joinreactdevske) for our telegram group chat
